version: '3.7'
services:
    nginx:
        image: nginx:1.17
        volumes:
            - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/log/nginx:/var/log/nginx/"
            - "./:/var/www/symfony4-news"
        ports:
            - "80:80"
        restart: always
        networks:
            - symfony4-news
    php-fpm:
        build: ./docker/bin/php-fpm
        restart: always
        volumes:
            - "./:/var/www/symfony4-news"
        networks:
            - symfony4-news
    postgres:
        image: postgres:12
        environment:
            POSTGRES_DB: symfony4-news
            POSTGRES_PASSWORD: postgres
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - "db-symfony4-news:/var/lib/postgresql/data"
        networks:
            - symfony4-news
    adminer:
        image: adminer
        depends_on:
            - postgres
        restart: always
        ports:
            - '127.0.0.1:8080:8080'
        networks:
            - symfony4-news
networks:
    symfony4-news:
volumes:
    db-symfony4-news: